# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20160915_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='itemScore',
            field=models.IntegerField(db_column='itemscore', default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='itemTime',
            field=models.IntegerField(db_column='itemtime', default=-1),
            preserve_default=False,
        ),
    ]
